name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - {dockerfile: 'Dockerfile', tag: 'nginx'}
          - {dockerfile: 'Dockerfile-alpine', tag: 'nginx-alpine', latest: true}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.config.dockerfile }}
          push: true
          tags: |
            binbashing/owasp-crs-ngxblocker:${{ matrix.config.tag }}
            binbashing/owasp-crs-ngxblocker:${{ github.sha }}-${{ matrix.config.tag }}
            ${{ matrix.config.latest && 'binbashing/owasp-crs-ngxblocker:latest' || '' }}
          platforms: linux/amd64,linux/arm64